Controllers/BookController.cs
using LibraryManagement.Models;
using Microsoft.AspNetCore.Mvc;
using LibraryManagement.Repositories;
using Microsoft.EntityFrameworkCore;

namespace LibraryManagement.Controllers
{
    public class BookController : Controller
    {

        private IUserRepository userRepository;
        private IBookRepository bookRepository;
        public BookController(IBookRepository _bookRepository, IUserRepository _userRepository)
        {
            bookRepository = _bookRepository;
            userRepository = _userRepository;
        }
        // GET: BookController
        public ActionResult Index()
        {
            return View(bookRepository.getBooks());
        }

        // GET: BookController/Details/5
        public ActionResult Details(int id)
        {
            return View(bookRepository.GetBook(id));
        }

        // GET: BookController/Create
        public ActionResult Create()
        {
            return View(new Book());
        }

        // POST: BookController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Book bookModel)
        {
                bookRepository.Add(bookModel);
                return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        // GET: BookController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(bookRepository.GetBook(id));
        }

        // POST: BookController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Book bookModel)
        {
            try{
                bookRepository.Update(id, bookModel);
            }
            catch (DbUpdateConcurrencyException ex){
                TempData["MessageErr"] = $"Could not write to database. Error: {ex.Message}!";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        // GET: BookController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(bookRepository.GetBook(id));
        }

        // POST: BookController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Book bookModel)
        {
            bookRepository.Delete(id);
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        public ActionResult EditDeleteList()
        {
            return View(bookRepository.getBooks());
        }
        public ActionResult BooksToReserve()
        {
            return View(bookRepository.getBooks());
        }

        [HttpPost]
        public ActionResult Reserve(int id, byte[] timestamp)
        { 

            string? login = HttpContext.Session.GetString("login");
            if (!string.IsNullOrEmpty(login))
            {
                User? user = userRepository.GetUser(login);
                try{
                    bookRepository.ReserveBook(id, user, timestamp);
                }
                catch (DbUpdateConcurrencyException ex){
                    TempData["MessageErr"] = $"Could not write to database. Error: {ex.Message}!";
                    return RedirectToAction(nameof(HomeController.Index), "Home");
                }
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
            else
                return View();

        }

        public ActionResult BooksToLease()
        {
            return View(bookRepository.getBooks());
        }

        public ActionResult Lease(int id)
        {
            return View(bookRepository.GetBook(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Lease(int id, Book bookModel)
        {
            bookRepository.LeaseBook(id, bookModel);
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        public ActionResult BooksToReturn()
        {
            return View(bookRepository.getBooks());
        }
        public ActionResult ReturnBook(int id)
        {
            bookRepository.ReturnBook(id);
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        public ActionResult SearchBook(string? searching)
        {
            return View(bookRepository.Searching(searching));
        }

        public ActionResult UserReservedBooks()
        {
             string? login = HttpContext.Session.GetString("login");
             return View(bookRepository.GetReservedBooks(login));
        }
        public ActionResult UndoReserve(int id)
        {
            bookRepository.UndoReserve(id);
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
    }
}

Controllers/UserController.cs
using LibraryManagement.Models;
using LibraryManagement.Repositories;
using LibraryManagement.Services;
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagement.Controllers
{ 
    public class UserController : Controller
    {
        private readonly IUserRepository userRepository;
        private UserService userService;

        public UserController(UserService _userService, IUserRepository _userRepository)
        {
            userService = _userService;
            userRepository = _userRepository;
        }

        public ActionResult Index()
        {
            return View(userRepository.getUsers());
        }

        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(string login, string password, string password_repeat)
        {
            User? user = userService.Register(login, password, password_repeat);
            if (user is not null && user.Login is not null)
            {
                TempData["Message"] = "Zostałeś zarejestrowany.";
                HttpContext.Session.SetString("login", login);
                HttpContext.Session.SetString("isSuperUser", user.IsSuperUser ? "true" : "false");

                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
            else
            {
                TempData["MessageErr"] = "Rejestracja nie powiodła się.";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
        }
        public ActionResult Logout()
        {
            HttpContext.Session.Clear();
            TempData["Message"] = "Zostałeś wylogowany.";
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string login, string password)
        {
            User? user = userService.Login(login, password);
            if (user is not null)
            {
                TempData["Message"] = "Zostałeś zalogowany.";
                HttpContext.Session.SetString("login", login);
                HttpContext.Session.SetString("isSuperUser", user.IsSuperUser ? "true" : "false");
            }
            else
            {
                TempData["MessageErr"] = "Logowanie nie powiodło się.";
            }
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
        public ActionResult DeleteAccountView()
        {
            return View();
        }

        public ActionResult DeleteAccount()
        {


            string? login = HttpContext.Session.GetString("login");
            if (!string.IsNullOrEmpty(login))
            {
                User? user = userRepository.GetUser(login);
                if (user is not null && user.Books is not null && user.Books.Count() == 0)
                {
                    TempData["Message"] = "Konto zostało usunięte.";
                    userRepository.Delete(user.UserID);
                    HttpContext.Session.Clear();
                }
                else
                {
                    TempData["MessageErr"] = "Nie można usunąć konta, bo są do niego przypisane książki.";
                }
            }
            else
            {
                TempData["MessageErr"] = "Nie udało się usunąć konta.";
            }
            return RedirectToAction(nameof(HomeController.Index), "Home");
 
        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LibraryManagement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Strona główna</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Lista książek</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav navbar-text navbar-right">
                        @if (@ViewBag.login is null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Zaloguj się</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Zarejestruj się</a>
                            </li>
                        } else{
                            @if (@ViewBag.isSuperUser == "false"){
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="DeleteAccountView">Usuń konto</a>
                                </li>
                            }

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Wyloguj się</a>
                            </li>
                        }
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (@TempData["Message"] is not null)
            {
                <div class="alert alert-secondary text-center" role="alert">
                    @TempData["Message"]
                </div>
            }
            @if (@TempData["MessageErr"] is not null)
            {
                <div class="alert alert-danger text-center" role="alert">
                    @TempData["MessageErr"]
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LibraryManagement
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>